hostservices:
  restserver:
    host: "127.0.0.1"
    port: "7000"
    state_dir: "/run/chv-lambda"
    bridge_name: "br0"
    bridge_ip: "10.20.1.1/24"
    bridge_subnet: "10.20.1.0/24"
    chv_bin: "./resources/bin/cloud-hypervisor"
    kernel: "./resources/bin/vmlinux.bin"
    rootfs: "./out/chv-guestrootfs-ext4.img"
  client:
    server_host: "127.0.0.1"
    server_port: "7000"
