hostservices:
  restserver:
    host: "127.0.0.1"
    port: "7000"
    state_dir: "/run/chv-starter-pack"
    bridge_name: "br0"
    bridge_ip: "10.20.1.1/24"
    bridge_subnet: "10.20.1.0/24"
    chv_bin: "./resources/bin/cloud-hypervisor"
    kernel: "./resources/bin/vmlinux.bin"
    rootfs: "./out/chv-guestrootfs-ext4.img"
    port_forwards:
      - host_port: "4030"
        guest_port: "4030"
      - host_port: "4031"
        guest_port: "4031"
      - host_port: "5901"
        guest_port: "5901"
      - host_port: "5902"
        guest_port: "5902"
      - host_port: "3389"
        guest_port: "3389"
  client:
    server_host: "127.0.0.1"
    server_port: "7000"
guestservices:
  codeserver:
    port: "4030"
  cmdserver:
    port: "4031"
