hostservices:
  restserver:
    host: "127.0.0.1"
    port: "7000"
    state_dir: "./vm-state"
    bridge_name: "br0"
    bridge_ip: "10.20.1.1/24"
    bridge_subnet: "10.20.1.0/24"
    chv_bin: "./resources/bin/cloud-hypervisor"
    kernel: "./resources/bin/vmlinux.bin"
    rootfs: "./out/chv-guestrootfs-ext4.img"
    initramfs: "./out/initramfs.cpio.gz"
    port_forwards:
      - port: "4030"
        description: "code"
      - port: "5901"
        description: "gui"
    stateful_size_in_mb: "8192"
    guest_mem_percentage: "50"
  client:
    server_host: "127.0.0.1"
    server_port: "7000"
guestservices:
  codeserver:
    port: "4030"
  cmdserver:
    port: "4031"
