openapi: 3.0.0
info:
  title: VM Management API
  description: API for managing VMs via REST endpoints.
  version: 1.0.0
servers:
  - url: http://{host}:{port}
    description: Development server
    variables:
      host:
        default: localhost
      port:
        default: "8080"
paths:
  /vms:
    get:
      summary: List all VMs
      responses:
        '200':
          description: List of all VMs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAllVMsResponse'
        '500':
          description: Internal server error
    post:
      summary: Start a VM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartVMRequest'
      responses:
        '200':
          description: Successfully started VM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartVMResponse'
        '400':
          description: Invalid request body
        '500':
          description: Internal server error
    delete:
      summary: Destroy all VMs
      responses:
        '200':
          description: Successfully destroyed all VMs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DestroyAllVMsResponse'
        '500':
          description: Internal server error
  /vms/{name}:
    get:
      summary: Get details of a specific VM
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the VM
          schema:
            type: string
      responses:
        '200':
          description: VM details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListVMResponse'
        '500':
          description: Internal server error
    patch:
      summary: Update the state of a specific VM
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the VM
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [stopped]
                  description: Action to perform on the VM
      responses:
        '200':
          description: Successfully updated VM state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VMResponse'
        '400':
          description: Invalid request body
        '404':
          description: VM not found
        '500':
          description: Internal server error
    delete:
      summary: Destroy a specific VM
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the VM to destroy
          schema:
            type: string
      responses:
        '200':
          description: Successfully destroyed VM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VMResponse'
        '404':
          description: VM not found
        '500':
          description: Internal server error
  /vms/{name}/snapshots:
    post:
      summary: Create a snapshot of a VM
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the VM to snapshot
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                outputFile:
                  type: string
                  description: Path where the snapshot should be saved
      responses:
        '200':
          description: Successfully created snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VMResponse'
        '400':
          description: Invalid request body
        '404':
          description: VM not found
        '500':
          description: Internal server error
components:
  schemas:
    StartVMRequest:
      type: object
      properties:
        vmName:
          type: string
          description: Name of the VM to start
        kernel:
          type: string
          description: Path of the kernel image to be used
        rootfs:
          type: string
          description: Path of the rootfs image to be used
        entryPoint:
          type: string
          description: Optional entry point to start in the VM upon boot
        snapshotPath:
          type: string
          description: Optional path to restore from a snapshot. If provided, kernel and rootfs are ignored
    StartVMResponse:
      type: object
      properties:
        vmName:
          type: string
        status:
          type: string
        ip:
          type: string
        tapDeviceName:
          type: string
        codeServerPort:
          type: string
        portForwards:
          type: array
          items:
            type: object
            properties:
              hostPort:
                type: string
              guestPort:
                type: string
    VMRequest:
      type: object
      properties:
        vmName:
          type: string
          description: Name of the VM
    VMResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    DestroyAllVMsResponse:
      type: object
      properties:
        success:
          type: boolean
    ListAllVMsResponse:
      type: object
      properties:
        vms:
          type: array
          items:
            type: object
            properties:
              vmName:
                type: string
              status:
                type: string
              ip:
                type: string
              tapDeviceName:
                type: string
    ListVMResponse:
      type: object
      properties:
        vmName:
          type: string
        status:
          type: string
        ip:
          type: string
        tapDeviceName:
          type: string
    VMSnapshotRequest:
      type: object
      properties:
        vmName:
          type: string
          description: Name of the VM to snapshot
        outputFile:
          type: string
          description: Path where the snapshot should be saved
      required:
        - vmName
    VMSnapshotResponse:
      type: object
      properties:
        success:
          type: boolean
    VMRestoreRequest:
      type: object
      properties:
        vmName:
          type: string
          description: Name to give to the restored VM
        snapshotPath:
          type: string
          description: Path to the snapshot directory to restore from
      required:
        - vmName
        - snapshotPath
    VMRestoreResponse:
      type: object
      properties:
        success:
          type: boolean

